name: "Pull Request Documentation Check"
on: 
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        build-command: "make api && make html"