name: Formatting

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run YAPF to test if python code is correctly formatted
      uses: AlexanderMelde/yapf-action@master
      with:
        args: --verbose --recursive --style google